version: '3.9'
services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
  frontend:
    build: ../frontend
    ports:
      - "3000:80"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
